version: '3.8'
services:
  fipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: fipe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fipe_db
    ports:
      - "5432:5432"